/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rasterimagefilters;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jedrek
 */
public class kernelInputDialog extends javax.swing.JDialog {
    private int[][] kernel;
    private int kernelWidth, kernelHeight;
    private Anchor anchor = new Anchor();
    private int offset;
    /**
     * Creates new form kernelInputDialog
     */
    public kernelInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        initComponents();
    }
    
    public int[][] getKernel(){
        return this.kernel;
    }
    
    public Anchor getAnchor(){
        return anchor;
    }
    
    public int getOffset(){
        return offset;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKernelWidth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKernelHeight = new javax.swing.JTextField();
        buttonGenerateCustomKernel = new javax.swing.JButton();
        panelCreateKernel = new javax.swing.JPanel();
        buttonSaveCustomKernel = new javax.swing.JButton();
        buttonCloseKernelCreator = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAnchorX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAnchorY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOffset = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("input kernel dimensions: ");

        jLabel2.setText(" x");

        buttonGenerateCustomKernel.setText("create kernel");
        buttonGenerateCustomKernel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateCustomKernelActionPerformed(evt);
            }
        });

        panelCreateKernel.setAutoscrolls(true);
        panelCreateKernel.setLayout(new java.awt.BorderLayout());

        buttonSaveCustomKernel.setText("Save");
        buttonSaveCustomKernel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveCustomKernelActionPerformed(evt);
            }
        });

        buttonCloseKernelCreator.setText("Close");
        buttonCloseKernelCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseKernelCreatorActionPerformed(evt);
            }
        });

        jLabel3.setText("anchor:");

        jLabel4.setText(" x ");

        jLabel5.setText("offset: ");

        txtOffset.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKernelWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKernelHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnchorX, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnchorY, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGenerateCustomKernel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonSaveCustomKernel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCloseKernelCreator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelCreateKernel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKernelWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtKernelHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGenerateCustomKernel)
                    .addComponent(jLabel3)
                    .addComponent(txtAnchorX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnchorY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCreateKernel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSaveCustomKernel)
                    .addComponent(buttonCloseKernelCreator)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseKernelCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseKernelCreatorActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCloseKernelCreatorActionPerformed

    private void buttonGenerateCustomKernelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateCustomKernelActionPerformed
        try{
            kernelWidth = Integer.parseInt(txtKernelWidth.getText());
            kernelHeight = Integer.parseInt(txtKernelHeight.getText());
            anchor.x = Integer.parseInt(txtAnchorX.getText());
            anchor.y = Integer.parseInt(txtAnchorY.getText());
            offset = Integer.parseInt(txtOffset.getText());
            if(anchor.x <  1 || anchor.x > kernelWidth || anchor.y < 1|| anchor.y > kernelHeight || 
                    kernelWidth < 1 || kernelWidth > 15 || kernelHeight < 1 || kernelHeight > 15)
                throw new Exception("Wrong inputs");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Wrong input values","error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        panelCreateKernel.removeAll();  
        panelCreateKernel.setLayout(new GridLayout(kernelHeight, kernelWidth));
        //panelCreateKernel.setSize(new Dimension(400, 400));
         for (int i = 0; i < kernelWidth*kernelHeight; i++){
            JTextField label = new JTextField("1");
            label.setVisible(true);
            
            panelCreateKernel.add(label);
            if(((anchor.y-1)*kernelWidth + (anchor.x-1)) == i)
                label.setBackground(Color.magenta);
        }
        panelCreateKernel.setVisible(true);
        this.pack();
    }//GEN-LAST:event_buttonGenerateCustomKernelActionPerformed

    private void buttonSaveCustomKernelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveCustomKernelActionPerformed
        Component[] arr = panelCreateKernel.getComponents();
        kernel = new int[kernelWidth][kernelHeight];
        int x, y;
        JTextField t;
        for(int i=0; i < arr.length; i++){
            x = i%kernelWidth;
            y = (int) Math.floor(i/kernelWidth);
            try{
                t = (JTextField)arr[i];
                kernel[x][y] = Integer.parseInt(t.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Kernel values have to be integers.","error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        this.dispose();
    }//GEN-LAST:event_buttonSaveCustomKernelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kernelInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kernelInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kernelInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kernelInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                kernelInputDialog dialog = new kernelInputDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCloseKernelCreator;
    private javax.swing.JButton buttonGenerateCustomKernel;
    private javax.swing.JButton buttonSaveCustomKernel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelCreateKernel;
    private javax.swing.JTextField txtAnchorX;
    private javax.swing.JTextField txtAnchorY;
    private javax.swing.JTextField txtKernelHeight;
    private javax.swing.JTextField txtKernelWidth;
    private javax.swing.JTextField txtOffset;
    // End of variables declaration//GEN-END:variables
}
